### ISSUE TITLE
onHeadersReceived does not support influencing the browser's cache

### ISSUE THREAD

**Issue by timing** [mubaidr/Speed-up-Browsing#9]
This is extension is a nice idea however according to the [documentation](https://developer.chrome.com/extensions/webRequest) the onHeadersReceived does not support influencing the cache. So in the inspector everything looks good (the headers have an improved cache control), but the next request is just using the original cache-control headers.

```
onHeadersReceived (optionally synchronous)
Fires each time that an HTTP(S) response header is received. Due to redirects and authentication requests this can happen multiple times per request. This event is intended to allow extensions to add, modify, and delete response headers, such as incoming Content-Type headers. The caching directives are processed before this event is triggered, so modifying headers such as Cache-Control has no influence on the browser's cache. It also allows you to cancel or redirect the request.
```

**Comment by mubaidr** [comment]
Interesting! 🤔  But I have seen this working. For example, sometimes websites will show always older content (I have to disable this extension to be able to see new one), this even happens for live development localhost servers. 

But according to the documentation, I have to revisit the code again, to find better more compatible approach for this extension.

**Comment by Denebulas** [comment]
Any update on this? How to test cache easily? I find only online tests for your website

**Comment by mubaidr** [comment]
Unfortunately, I have no idea. Only way is to manually test. Load a website with speedup browsing 2,3 times and check in developer tools for network requests (maximum should be from cache) and then test again by disabling extension.
